// Had better be added to .gitignore file for security reasons
object Secret {

    const val GOOGLE_MAPS_KEY = "AIzaSyDGbu5l1yTHYkn_HqF3LHJKOMcDNOC8GcA"

    const val FOURSQUARE_CLIENT_ID = "4WFDGRA3G5BPIN0PBNYQBGEKOKJPKSQH205OL1XJLEGI4UPG"
    const val FOURSQUARE_SECRET = "HDF1YWNZKGQD5WDOVT53B3TIVHZNHSEXP3ISDYRTJZ1UFWR3"

}